version: "3.8"
services:
  web-gabananet:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: Web-GABANANET
    ports:
      - "8382:80" # Mapeo de puertos
    networks:
      - webnet
    restart: always
networks:
  webnet:
    driver: bridge
