services:
  web-gabananet:
    container_name: WEB_CLIENTE__GABANANET
    build: .
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 256M
        reservations:
          cpus: '0.25'
          memory: 128M
    ports:
      - "8383:80"
    restart: unless-stopped
    networks:
      - gabananet_network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

networks:
  gabananet_network:
    driver: bridge
